[project]
name = "helix"
queries = "./db/"

[local.dev]
port = 6969
build_mode = "debug"

[cloud.staging.ecr]
repository_name = "helix-helix-staging"
region = "us-east-1"
registry_url = "846640070231.dkr.ecr.us-east-1.amazonaws.com"
auth_type = "AwsCli"
build_mode = "debug"
